---
title: "Texas Schools & Racist Names Impact on Student Achievement"
output: html_notebook
---


```{r}
library(readr)

staar <- read_csv("~/Box Sync/R/Texas Schools/STAAR.csv")
STAAR_colnames <- read_csv("~/Box Sync/R/Texas Schools/STAAR_colnames.csv")
campus <- read_csv("~/Box Sync/R/Texas Schools/CampusID.csv")

STAAR_colnames$NAME <- gsub("\xca","",STAAR_colnames$NAME)
STAAR_colnames$LABEL <- gsub("\xca","",STAAR_colnames$LABEL)
names(staar) <- STAAR_colnames$LABEL[match(names(staar),STAAR_colnames$NAME)]

staar$campus <- campus$CAMPNAME[match(staar$`Campus Number`,campus$CAMPUS)]
staar$racist <- campus$RACISTNAME[match(staar$`Campus Number`,campus$CAMPUS)]

scores <- staar[,c(1,272,273,2,3,4,12,13,15,16,20,21,22,30,31,33,34,38,39,40,48,49,51,52)]

scores[,4:24] <- lapply(scores[,4:24], as.numeric)
scores$racist <- as.factor(scores$racist)
scores[scores=="-1"] <- NA

scores$readgap <- scores$`All Students, EOC Reading I Rate` - scores$`African American, EOC Reading I Rate`





```
dropout rate analysis
```{r}
library(readxl)
library(readr)
dropoutRates <- read_excel("~/Box Sync/R/Texas Schools/dropoutRates.xls")
campus <- read_csv("~/Box Sync/R/Texas Schools/CampusID.csv")      

campus$dropoutAll <- dropoutRates$dropoutHSAllStudents[match(campus$CAMPUS,dropoutRates$campus)]
campus$dropoutAA <- as.integer(dropoutRates$dropoutHSAfricanAmerican[match(campus$CAMPUS,dropoutRates$campus)])
campus$dropoutDiffAA <- as.numeric(campus$dropoutAA - campus$dropoutAll)

campusHS <- subset(campus, GRDTYPE == 'S')

mn <- aggregate(dropoutAA ~ RACISTNAME, data = campusHS, mean)
md <- aggregate(dropoutAA ~ RACISTNAME, data = campusHS, median)
stdev <- sd(campusHS$dropoutAA, na.rm = TRUE)

summary(lm(dropoutAA ~ RACISTNAME, data = campusHS))

```

